(()=>{
const hidden=document.getElementById('accessoires');if(!hidden)return;
const TXT={fr:{title:"AJOUT D'ACCESSOIRES",category:'Catégorie',categoryPick:'Sélectionnez une catégorie…',brand:'Fournisseur / marque',brandPick:"Sélectionnez d'abord une catégorie…",brandChoose:'Sélectionnez une marque / provenance…',type:'Modèle / type',typePick:"Sélectionnez d'abord une marque…",typeChoose:'Sélectionnez le type d’accessoire…',add:'Ajouter cet accessoire',included:"Accessoires inclus dans l'évaluation :",empty:'Aucun accessoire ajouté pour le moment.',unknown:'Je ne sais pas / afficher tous',oem:"OEM / pièce d'origine",other:'Autre / générique',note:"Pour Magic Book, la marque sert surtout à préciser la qualité et la provenance. La valeur monétaire reste dépréciée selon l’âge et l’état de la machine, puis plafonnée pour éviter une surévaluation.",details:'Détails des accessoires',detected:'Type détecté',unknownType:'Type non identifié — toutes les catégories sont affichées.',showAll:'Afficher toutes les catégories',autoFilter:'Revenir au filtre automatique',outside:'hors filtre automatique',allShown:'Toutes les catégories sont affichées'},en:{title:'ADD ACCESSORIES',category:'Category',categoryPick:'Select a category…',brand:'Supplier / brand',brandPick:'Select a category first…',brandChoose:'Select a brand / source…',type:'Model / type',typePick:'Select a brand first…',typeChoose:'Select the accessory type…',add:'Add this accessory',included:'Accessories included in the evaluation:',empty:'No accessory added yet.',unknown:"I don't know / show all",oem:'OEM / genuine part',other:'Other / generic',note:'For Magic Book, the brand mainly identifies quality and source. Monetary value is still depreciated by vehicle age and condition, then capped to avoid overvaluation.',details:'Accessory details',detected:'Detected type',unknownType:'Vehicle type not identified — all categories are shown.',showAll:'Show all categories',autoFilter:'Return to automatic filter',outside:'outside automatic filter',allShown:'All categories are shown'}};
const CATS=[
{id:'major',fr:'Valeur majeure / transformation',en:'Major value / transformation',items:['chenilles','cabine-complete','cabine-chauffee','suspension-elka-fox','moteur-refait','direction-assistee']},
{id:'utility',fr:'Utilité / travail / hiver',en:'Utility / work / winter',items:['treuil','gratte','souffleuse','coffre-arriere','coffre-avant','support-fusil']},
{id:'cab',fr:'Cabine / confort',en:'Cab / comfort',items:['pare-brise-complet','demi-pare-brise','toit','portieres','poignees-chauffantes']},
{id:'protection',fr:'Protection / châssis',en:'Protection / chassis',items:['bumper-avant','bumper-arriere','skid-plate','protecteur-bras','rock-sliders']},
{id:'rolling',fr:'Roues / pneus / roulement',en:'Wheels / tires / rolling',items:['pneus-mags','elargisseurs']},
{id:'electrical',fr:'Éclairage / électronique / audio',en:'Lighting / electronics / audio',items:['barre-led','systeme-son']},
{id:'moto',fr:'Moto / motocross',en:'Motorcycle / motocross',items:['ligne-echappement','silencieux','kit-graphique','embrayage-rekluse','protege-mains','guidon-pro','housse-siege','valises-moto','crash-bars']},
{id:'snow',fr:'Motoneige',en:'Snowmobile',items:['demarreur-electrique','chenille-crampons','sac-tunnel','grattoirs-glace','kit-clutch']},
{id:'pwc',fr:'Motomarine / Waverunner',en:'Personal watercraft / Waverunner',items:['housse-transport','systeme-audio-marin','echelle','support-wake','gps-sondeur']}
];
const B={
'chenilles':['OEM','Camso','Kimpex','OTHER'],'cabine-complete':['OEM','SuperATV','Seizmik','Kimpex','OTHER'],'cabine-chauffee':['OEM','SuperATV','Inferno','Kimpex','OTHER'],'suspension-elka-fox':['Elka','Fox','Walker Evans','OTHER'],'moteur-refait':['OEM','Hot Rods','Athena','OTHER'],'direction-assistee':['OEM','SuperATV','Kimpex','OTHER'],
'treuil':['WARN','Kimpex','SuperATV','OEM','OTHER'],'gratte':['Kimpex','Kolpin','WARN','OEM','OTHER'],'souffleuse':['Bercomac','Kimpex','OTHER'],'coffre-arriere':['OEM','Kimpex','Kolpin','LinQ','OTHER'],'coffre-avant':['OEM','Kimpex','Kolpin','OTHER'],'support-fusil':['Kolpin','Kimpex','OTHER'],
'pare-brise-complet':['OEM','Kimpex','SuperATV','Seizmik','OTHER'],'demi-pare-brise':['OEM','Kimpex','SuperATV','OTHER'],'toit':['OEM','Kimpex','SuperATV','OTHER'],'portieres':['OEM','SuperATV','Seizmik','Kimpex','OTHER'],'poignees-chauffantes':['OEM','Oxford','Kimpex','OTHER'],
'bumper-avant':['OEM','SuperATV','Rival','Kimpex','OTHER'],'bumper-arriere':['OEM','SuperATV','Rival','Kimpex','OTHER'],'skid-plate':['OEM','Rival','SuperATV','Kimpex','OTHER'],'protecteur-bras':['OEM','Rival','SuperATV','Kimpex','OTHER'],'rock-sliders':['OEM','SuperATV','Rival','OTHER'],
'pneus-mags':['OEM','Maxxis','ITP','System 3','MSA','Method','OTHER'],'elargisseurs':['SuperATV','High Lifter','Kimpex','OTHER'],
'barre-led':['Rigid Industries','Baja Designs','Kimpex','OEM','OTHER'],'systeme-son':['OEM','SSV Works','Rockford Fosgate','Wet Sounds','OTHER'],
'ligne-echappement':['FMF','Pro Circuit','Akrapovič','Yoshimura','Graves','OEM','OTHER'],'silencieux':['FMF','Pro Circuit','Akrapovič','Yoshimura','Graves','OEM','OTHER'],'kit-graphique':['Kutvek','Factory Effex',"D'Cor",'OTHER'],'embrayage-rekluse':['Rekluse','Hinson','OEM','OTHER'],'protege-mains':['Acerbis','Cycra','Barkbusters','OEM','OTHER'],'guidon-pro':['Renthal','ProTaper','ODI','OTHER'],'housse-siege':['Guts','Factory Effex','OTHER'],'valises-moto':['Givi','SHAD','SW-Motech','OEM','OTHER'],'crash-bars':['SW-Motech','Givi','OEM','OTHER'],
'demarreur-electrique':['OEM','Kimpex','OTHER'],'chenille-crampons':['Camso',"Woody's",'Stud Boy','OEM','OTHER'],'sac-tunnel':['LinQ','OEM','Kimpex','OTHER'],'grattoirs-glace':['OEM','Kimpex','OTHER'],'kit-clutch':['Dalton','EPI','OEM','OTHER'],
'housse-transport':['OEM','Yamaha','Sea-Doo','Kawasaki','OTHER'],'systeme-audio-marin':['OEM','JL Audio','Fusion','Rockford Fosgate','OTHER'],'echelle':['OEM','Yamaha','Sea-Doo','Kawasaki','OTHER'],'support-wake':['OEM','Yamaha','Sea-Doo','LinQ','OTHER'],'gps-sondeur':['Garmin','Humminbird','Lowrance','OEM','OTHER']
};
const TYPE_LABELS={offroad:{fr:'VTT / côte-à-côte',en:'ATV / side-by-side'},moto:{fr:'Moto / motocross',en:'Motorcycle / motocross'},snow:{fr:'Motoneige',en:'Snowmobile'},pwc:{fr:'Motomarine',en:'Personal watercraft'},boat:{fr:'Bateau / ponton',en:'Boat / pontoon'},unknown:{fr:'Non identifié',en:'Unknown'}};
const TYPE_ITEMS={
offroad:['chenilles','cabine-complete','cabine-chauffee','suspension-elka-fox','moteur-refait','direction-assistee','treuil','gratte','souffleuse','coffre-arriere','coffre-avant','support-fusil','pare-brise-complet','demi-pare-brise','toit','portieres','poignees-chauffantes','bumper-avant','bumper-arriere','skid-plate','protecteur-bras','rock-sliders','pneus-mags','elargisseurs','barre-led','systeme-son'],
moto:['suspension-elka-fox','moteur-refait','ligne-echappement','silencieux','kit-graphique','embrayage-rekluse','protege-mains','guidon-pro','housse-siege','valises-moto','crash-bars'],
snow:['moteur-refait','demarreur-electrique','chenille-crampons','sac-tunnel','grattoirs-glace','kit-clutch'],
pwc:['moteur-refait','housse-transport','systeme-audio-marin','echelle','support-wake','gps-sondeur'],
boat:['housse-transport','systeme-audio-marin','echelle','support-wake','gps-sondeur']
};
const el=id=>document.getElementById(id),L=()=>typeof lang!=='undefined'&&lang==='en'?'en':'fr',tx=k=>TXT[L()][k];let meta={},currentType='unknown',showAll=false;
function normalize(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function detectVehicleType(){const brand=normalize(el('marque')?.value),model=normalize(el('modele')?.value);const m=` ${model} `;
 if(/\b(ponton|pontoon|bowrider|deck boat|chaloupe|bateau)\b/.test(m))return'boat';
 if(/\b(waverunner|wave runner|jetblaster|jet blaster|superjet|gp1800|gp svho|fx svho|fx ho|spark|gti|gtx|rxt|rxp|fish pro|wake pro|jet ski)\b/.test(m)||/\b(vx|stx 160|ultra 310)\b/.test(m))return'pwc';
 if(/\b(sidewinder|srx|viper|phazer|apex|vector|nytro|mountain max|rmk|switchback|indy|norseman|thundercat|riot|blast|pantera)\b/.test(m)||/\bzr\s?\d/.test(m))return'snow';
 if(/\b(grizzly|kodiak|raptor|yfz|wolverine|viking|yxz|rhino|sportsman|scrambler|ranger|rzr|general|outlaw|outlander|defender|maverick|commander|rancher|foreman|rubicon|rincon|trx|talon|pioneer|brute force|teryx|mule|kfx|kingquad|quadsport|ltz|lt-z|alterra|prowler|wildcat|pathcross|workcross)\b/.test(m))return'offroad';
 if(/\b(yz\s?\d|wr\s?\d|tenere|mt[- ]?\d|yzf-r|xsr|tracer|crf|cbr|rebel|africa twin|gold ?wing|grom|kx\s?\d|klx|ninja|versys|vulcan|eliminator|rm-z|rmz|gsx|v-strom|dr-z|drz|hayabusa|boulevard|duke|adventure|exc|sx|xc|smr|vitpilen|svartpilen|spyder|ryker|street glide|road glide|sportster|pan america|softail)\b/.test(m))return'moto';
 if(['princecraft','g3 boats','lund','crestliner','commere','sylvan','starcraft','bennington'].includes(brand))return'boat';
 if(brand==='sea-doo')return'pwc';if(brand==='ski-doo')return'snow';
 if(['harley-davidson','bmw motorrad','ktm','husqvarna','gasgas'].includes(brand))return'moto';
 if(brand==='can-am')return/\b(spyder|ryker)\b/.test(m)?'moto':'offroad';
 if(brand==='arctic cat')return/\b(alterra|prowler|wildcat)\b/.test(m)?'offroad':'snow';
 return'unknown'}
function allIds(){return CATS.flatMap(c=>c.items)}
function allowedSet(){return new Set(showAll||currentType==='unknown'?allIds():(TYPE_ITEMS[currentType]||allIds()))}
function filteredCats(){const allow=allowedSet();return CATS.map(c=>({...c,items:c.items.filter(id=>allow.has(id))})).filter(c=>c.items.length)}
function baseOption(id){return Array.from(hidden.options).find(o=>o.value===id)}
function baseLabel(id){return baseOption(id)?.textContent||id}
function refValue(id){return Number(baseOption(id)?.dataset.ref||0)}
function brandLabel(v){if(v==='ANY')return tx('unknown');if(v==='OEM')return tx('oem');if(v==='OTHER')return tx('other');return v}
function catLabel(c){if(currentType==='boat'&&c.id==='pwc')return L()==='fr'?'Nautique / bateau':'Marine / boat';return L()==='fr'?c.fr:c.en}
function selectedDetailArray(){return Array.from(hidden.selectedOptions).map(o=>({id:o.value,brand:meta[o.value]?.brand||''}))}
function loadMeta(details){meta={};if(Array.isArray(details))details.forEach(d=>{if(d&&d.id)meta[d.id]={brand:String(d.brand||'')}})}
function restoreMetaFromDraft(){try{const p=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');loadMeta(p?.accessoire_details||[])}catch{}}
function optionsHtml(items,placeholder){return `<option value="" selected disabled>${esc(placeholder)}</option>`+items.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}
function populateCategories(keep=''){const cats=filteredCats();el('accCategory').innerHTML=optionsHtml(cats.map(c=>({value:c.id,label:catLabel(c)})),tx('categoryPick'));if(keep&&cats.some(c=>c.id===keep)){el('accCategory').value=keep;populateBrands()}else{el('accBrand').innerHTML=optionsHtml([],tx('brandPick'));el('accType').innerHTML=optionsHtml([],tx('typePick'));el('accBrand').disabled=true;el('accType').disabled=true;el('accAddBtn').disabled=true}}
function populateBrands(){const c=filteredCats().find(x=>x.id===el('accCategory').value);if(!c)return;const vals=[...new Set(c.items.flatMap(id=>B[id]||['OTHER']))];el('accBrand').innerHTML=optionsHtml([{value:'ANY',label:tx('unknown')},...vals.map(v=>({value:v,label:brandLabel(v)}))],tx('brandChoose'));el('accBrand').disabled=false;el('accType').innerHTML=optionsHtml([],tx('typePick'));el('accType').disabled=true;el('accAddBtn').disabled=true}
function populateTypes(){const c=filteredCats().find(x=>x.id===el('accCategory').value),brand=el('accBrand').value;if(!c||!brand)return;const ids=c.items.filter(id=>brand==='ANY'||(B[id]||[]).includes(brand));el('accType').innerHTML=optionsHtml(ids.map(id=>({value:id,label:baseLabel(id)})),tx('typeChoose'));el('accType').disabled=false;el('accAddBtn').disabled=true}
function renderStatus(){const label=TYPE_LABELS[currentType]?.[L()]||TYPE_LABELS.unknown[L()];const selected=Array.from(hidden.selectedOptions).map(o=>o.value),allow=allowedSet(),outside=showAll?[]:selected.filter(id=>!allow.has(id));let html=currentType==='unknown'?`<span class="warn">${esc(tx('unknownType'))}</span>`:`<b>${esc(tx('detected'))} :</b> ${esc(label)}`;if(showAll)html+=` · ${esc(tx('allShown'))}`;if(outside.length)html+=`<br><span class="warn">${outside.length} ${esc(tx('outside'))}</span>`;el('accVehicleType').innerHTML=html;el('accShowAll').textContent=showAll?tx('autoFilter'):tx('showAll')}
function renderTags(){const ids=Array.from(hidden.selectedOptions).map(o=>o.value),allow=allowedSet();el('accTags').innerHTML=ids.length?ids.map(id=>{const brand=meta[id]?.brand,outside=!showAll&&currentType!=='unknown'&&!allow.has(id);return `<div class="accessory-tag${outside?' outside-filter':''}" data-acc-tag="${esc(id)}"><div class="accessory-tag-text"><b>${esc(baseLabel(id))}</b><small>${brand?esc(brandLabel(brand))+' · ':''}${money(refValue(id))} réf.${outside?' · '+esc(tx('outside')):''}</small></div><button type="button" data-remove-acc="${esc(id)}" aria-label="Retirer">×</button></div>`}).join(''):`<div class="accessory-empty">${esc(tx('empty'))}</div>`;el('accTags').querySelectorAll('[data-remove-acc]').forEach(b=>b.onclick=()=>removeAccessory(b.dataset.removeAcc));renderStatus()}
function addAccessory(){const id=el('accType').value,brand=el('accBrand').value;if(!id)return;const o=baseOption(id);if(!o)return;o.selected=true;meta[id]={brand:brand==='ANY'?'':brand};hidden.dispatchEvent(new Event('change',{bubbles:true}));renderTags();el('accType').selectedIndex=0;el('accAddBtn').disabled=true}
function removeAccessory(id){const o=baseOption(id);if(o)o.selected=false;delete meta[id];hidden.dispatchEvent(new Event('change',{bubbles:true}));renderTags()}
function updateVehicleFilter(){const oldCat=el('accCategory').value,newType=detectVehicleType(),changed=newType!==currentType;currentType=newType;populateCategories(changed?'':oldCat);renderTags()}
function refreshText(){el('accTitle').textContent=tx('title');el('accCategoryLabel').textContent=tx('category');el('accBrandLabel').textContent=tx('brand');el('accTypeLabel').textContent=tx('type');el('accAddBtn').textContent=tx('add');el('accIncludedTitle').textContent=tx('included');el('accBuilderNote').innerHTML=`<strong>${esc(tx('note'))}</strong>`;const cat=el('accCategory').value,brand=el('accBrand').value;populateCategories(cat);if(cat&&el('accCategory').value===cat&&brand){el('accBrand').value=Array.from(el('accBrand').options).some(o=>o.value===brand)?brand:'ANY';populateTypes()}renderTags()}
function enrichResult(p){const details=Array.isArray(p?.accessoire_details)?p.accessoire_details:[];const shown=details.filter(d=>d?.id&&d?.brand);if(!shown.length)return;const first=document.querySelector('#cards .card');if(!first)return;first.querySelector('.accessory-brand-summary')?.remove();const box=document.createElement('div');box.className='accessory-brand-summary';box.innerHTML=`<b>${esc(tx('details'))}:</b><br>${shown.map(d=>`${esc(baseLabel(d.id))} — ${esc(brandLabel(d.brand))}`).join('<br>')}`;first.appendChild(box)}
try{const baseFormState=formState;formState=function(){const p=baseFormState();p.accessoire_details=selectedDetailArray();return p};const baseApiPayload=apiPayload;apiPayload=function(){const p=baseApiPayload();p.accessoire_details=selectedDetailArray();return p};const baseFillForm=fillForm;fillForm=function(p){loadMeta(p?.accessoire_details||[]);baseFillForm(p);setTimeout(()=>{updateVehicleFilter();renderTags()},0)};const baseSelectedLabels=selectedLabels;selectedLabels=function(){return Array.from(hidden.selectedOptions).map(o=>{const b=meta[o.value]?.brand;return b?`${o.textContent} (${brandLabel(b)})`:o.textContent})};const baseRender=render;render=function(data,p,save){baseRender(data,p,save);setTimeout(()=>enrichResult(p),0)}}catch(e){console.warn('Magic Book accessory bridge',e)}
restoreMetaFromDraft();currentType=detectVehicleType();populateCategories();refreshText();renderTags();el('accCategory').addEventListener('change',populateBrands);el('accBrand').addEventListener('change',populateTypes);el('accType').addEventListener('change',()=>{el('accAddBtn').disabled=!el('accType').value});el('accAddBtn').addEventListener('click',addAccessory);el('accShowAll').addEventListener('click',()=>{showAll=!showAll;populateCategories();renderTags()});el('marque').addEventListener('change',updateVehicleFilter);let modelTimer;el('modele').addEventListener('input',()=>{clearTimeout(modelTimer);modelTimer=setTimeout(updateVehicleFilter,120)});el('language').addEventListener('change',()=>setTimeout(refreshText,0));el('reset').addEventListener('click',()=>setTimeout(()=>{meta={};showAll=false;currentType=detectVehicleType();populateCategories();renderTags();try{saveDraft()}catch{}},0));
})();