(()=>{
const hidden=document.getElementById('accessoires');if(!hidden)return;
const TXT={fr:{title:"AJOUT D'ACCESSOIRES",category:'Catégorie',categoryPick:'Sélectionnez une catégorie…',brand:'Fournisseur / marque',brandPick:"Sélectionnez d'abord une catégorie…",brandChoose:'Sélectionnez une marque / provenance…',type:'Modèle / type',typePick:"Sélectionnez d'abord une marque…",typeChoose:'Sélectionnez le type d’accessoire…',add:'Ajouter cet accessoire',included:"Accessoires inclus dans l'évaluation :",empty:'Aucun accessoire ajouté pour le moment.',unknown:'Je ne sais pas / afficher tous',oem:"OEM / pièce d'origine",other:'Autre / générique',note:"Pour Magic Book, la marque sert surtout à préciser la qualité et la provenance. La valeur monétaire reste dépréciée selon l’âge et l’état de la machine, puis plafonnée pour éviter une surévaluation.",details:'Détails des accessoires'},en:{title:'ADD ACCESSORIES',category:'Category',categoryPick:'Select a category…',brand:'Supplier / brand',brandPick:'Select a category first…',brandChoose:'Select a brand / source…',type:'Model / type',typePick:'Select a brand first…',typeChoose:'Select the accessory type…',add:'Add this accessory',included:'Accessories included in the evaluation:',empty:'No accessory added yet.',unknown:"I don't know / show all",oem:'OEM / genuine part',other:'Other / generic',note:'For Magic Book, the brand mainly identifies quality and source. Monetary value is still depreciated by vehicle age and condition, then capped to avoid overvaluation.',details:'Accessory details'}};
const CATS=[
{id:'major',fr:'Valeur majeure / transformation',en:'Major value / transformation',items:['chenilles','cabine-complete','cabine-chauffee','suspension-elka-fox','moteur-refait','direction-assistee']},
{id:'utility',fr:'Utilité / travail / hiver',en:'Utility / work / winter',items:['treuil','gratte','souffleuse','coffre-arriere','coffre-avant','support-fusil']},
{id:'cab',fr:'Cabine / confort',en:'Cab / comfort',items:['pare-brise-complet','demi-pare-brise','toit','portieres','poignees-chauffantes']},
{id:'protection',fr:'Protection / châssis',en:'Protection / chassis',items:['bumper-avant','bumper-arriere','skid-plate','protecteur-bras','rock-sliders']},
{id:'rolling',fr:'Roues / pneus / roulement',en:'Wheels / tires / rolling',items:['pneus-mags','elargisseurs']},
{id:'electrical',fr:'Éclairage / électronique / audio',en:'Lighting / electronics / audio',items:['barre-led','systeme-son']},
{id:'moto',fr:'Moto / motocross',en:'Motorcycle / motocross',items:['ligne-echappement','silencieux','kit-graphique','embrayage-rekluse','protege-mains','guidon-pro','housse-siege','valises-moto','crash-bars']},
{id:'snow',fr:'Motoneige',en:'Snowmobile',items:['demarreur-electrique','chenille-crampons','sac-tunnel','grattoirs-glace','kit-clutch']},
{id:'pwc',fr:'Motomarine / Waverunner',en:'Personal watercraft / Waverunner',items:['housse-transport','systeme-audio-marin','echelle','support-wake','gps-sondeur']}
];
const B={
'chenilles':['OEM','Camso','Kimpex','OTHER'],'cabine-complete':['OEM','SuperATV','Seizmik','Kimpex','OTHER'],'cabine-chauffee':['OEM','SuperATV','Inferno','Kimpex','OTHER'],'suspension-elka-fox':['Elka','Fox','Walker Evans','OTHER'],'moteur-refait':['OEM','Hot Rods','Athena','OTHER'],'direction-assistee':['OEM','SuperATV','Kimpex','OTHER'],
'treuil':['WARN','Kimpex','SuperATV','OEM','OTHER'],'gratte':['Kimpex','Kolpin','WARN','OEM','OTHER'],'souffleuse':['Bercomac','Kimpex','OTHER'],'coffre-arriere':['OEM','Kimpex','Kolpin','LinQ','OTHER'],'coffre-avant':['OEM','Kimpex','Kolpin','OTHER'],'support-fusil':['Kolpin','Kimpex','OTHER'],
'pare-brise-complet':['OEM','Kimpex','SuperATV','Seizmik','OTHER'],'demi-pare-brise':['OEM','Kimpex','SuperATV','OTHER'],'toit':['OEM','Kimpex','SuperATV','OTHER'],'portieres':['OEM','SuperATV','Seizmik','Kimpex','OTHER'],'poignees-chauffantes':['OEM','Oxford','Kimpex','OTHER'],
'bumper-avant':['OEM','SuperATV','Rival','Kimpex','OTHER'],'bumper-arriere':['OEM','SuperATV','Rival','Kimpex','OTHER'],'skid-plate':['OEM','Rival','SuperATV','Kimpex','OTHER'],'protecteur-bras':['OEM','Rival','SuperATV','Kimpex','OTHER'],'rock-sliders':['OEM','SuperATV','Rival','OTHER'],
'pneus-mags':['OEM','Maxxis','ITP','System 3','MSA','Method','OTHER'],'elargisseurs':['SuperATV','High Lifter','Kimpex','OTHER'],
'barre-led':['Rigid Industries','Baja Designs','Kimpex','OEM','OTHER'],'systeme-son':['OEM','SSV Works','Rockford Fosgate','Wet Sounds','OTHER'],
'ligne-echappement':['FMF','Pro Circuit','Akrapovič','Yoshimura','Graves','OEM','OTHER'],'silencieux':['FMF','Pro Circuit','Akrapovič','Yoshimura','Graves','OEM','OTHER'],'kit-graphique':['Kutvek','Factory Effex',"D'Cor",'OTHER'],'embrayage-rekluse':['Rekluse','Hinson','OEM','OTHER'],'protege-mains':['Acerbis','Cycra','Barkbusters','OEM','OTHER'],'guidon-pro':['Renthal','ProTaper','ODI','OTHER'],'housse-siege':['Guts','Factory Effex','OTHER'],'valises-moto':['Givi','SHAD','SW-Motech','OEM','OTHER'],'crash-bars':['SW-Motech','Givi','OEM','OTHER'],
'demarreur-electrique':['OEM','Kimpex','OTHER'],'chenille-crampons':['Camso',"Woody's",'Stud Boy','OEM','OTHER'],'sac-tunnel':['LinQ','OEM','Kimpex','OTHER'],'grattoirs-glace':['OEM','Kimpex','OTHER'],'kit-clutch':['Dalton','EPI','OEM','OTHER'],
'housse-transport':['OEM','Yamaha','Sea-Doo','Kawasaki','OTHER'],'systeme-audio-marin':['OEM','JL Audio','Fusion','Rockford Fosgate','OTHER'],'echelle':['OEM','Yamaha','Sea-Doo','Kawasaki','OTHER'],'support-wake':['OEM','Yamaha','Sea-Doo','LinQ','OTHER'],'gps-sondeur':['Garmin','Humminbird','Lowrance','OEM','OTHER']
};
const el=id=>document.getElementById(id),L=()=>typeof lang!=='undefined'&&lang==='en'?'en':'fr',tx=k=>TXT[L()][k];let meta={};
function baseOption(id){return Array.from(hidden.options).find(o=>o.value===id)}
function baseLabel(id){return baseOption(id)?.textContent||id}
function refValue(id){return Number(baseOption(id)?.dataset.ref||0)}
function brandLabel(v){if(v==='ANY')return tx('unknown');if(v==='OEM')return tx('oem');if(v==='OTHER')return tx('other');return v}
function catLabel(c){return L()==='fr'?c.fr:c.en}
function selectedDetailArray(){return Array.from(hidden.selectedOptions).map(o=>({id:o.value,brand:meta[o.value]?.brand||''}))}
function loadMeta(details){meta={};if(Array.isArray(details))details.forEach(d=>{if(d&&d.id)meta[d.id]={brand:String(d.brand||'')}})}
function restoreMetaFromDraft(){try{const p=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');loadMeta(p?.accessoire_details||[])}catch{}}
function optionsHtml(items,placeholder){return `<option value="" selected disabled>${esc(placeholder)}</option>`+items.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')}
function populateCategories(){el('accCategory').innerHTML=optionsHtml(CATS.map(c=>({value:c.id,label:catLabel(c)})),tx('categoryPick'));el('accBrand').innerHTML=optionsHtml([],tx('brandPick'));el('accType').innerHTML=optionsHtml([],tx('typePick'));el('accBrand').disabled=true;el('accType').disabled=true;el('accAddBtn').disabled=true}
function populateBrands(){const c=CATS.find(x=>x.id===el('accCategory').value);if(!c)return;const vals=[...new Set(c.items.flatMap(id=>B[id]||['OTHER']))];el('accBrand').innerHTML=optionsHtml([{value:'ANY',label:tx('unknown')},...vals.map(v=>({value:v,label:brandLabel(v)}))],tx('brandChoose'));el('accBrand').disabled=false;el('accType').innerHTML=optionsHtml([],tx('typePick'));el('accType').disabled=true;el('accAddBtn').disabled=true}
function populateTypes(){const c=CATS.find(x=>x.id===el('accCategory').value),brand=el('accBrand').value;if(!c||!brand)return;const ids=c.items.filter(id=>brand==='ANY'||(B[id]||[]).includes(brand));el('accType').innerHTML=optionsHtml(ids.map(id=>({value:id,label:baseLabel(id)})),tx('typeChoose'));el('accType').disabled=false;el('accAddBtn').disabled=true}
function renderTags(){const ids=Array.from(hidden.selectedOptions).map(o=>o.value);el('accTags').innerHTML=ids.length?ids.map(id=>{const brand=meta[id]?.brand;return `<div class="accessory-tag" data-acc-tag="${esc(id)}"><div class="accessory-tag-text"><b>${esc(baseLabel(id))}</b><small>${brand?esc(brandLabel(brand))+' · ':''}${money(refValue(id))} réf.</small></div><button type="button" data-remove-acc="${esc(id)}" aria-label="Retirer">×</button></div>`}).join(''):`<div class="accessory-empty">${esc(tx('empty'))}</div>`;el('accTags').querySelectorAll('[data-remove-acc]').forEach(b=>b.onclick=()=>removeAccessory(b.dataset.removeAcc));}
function addAccessory(){const id=el('accType').value,brand=el('accBrand').value;if(!id)return;const o=baseOption(id);if(!o)return;o.selected=true;meta[id]={brand:brand==='ANY'?'':brand};hidden.dispatchEvent(new Event('change',{bubbles:true}));renderTags();el('accType').selectedIndex=0;el('accAddBtn').disabled=true}
function removeAccessory(id){const o=baseOption(id);if(o)o.selected=false;delete meta[id];hidden.dispatchEvent(new Event('change',{bubbles:true}));renderTags()}
function refreshText(){el('accTitle').textContent=tx('title');el('accCategoryLabel').textContent=tx('category');el('accBrandLabel').textContent=tx('brand');el('accTypeLabel').textContent=tx('type');el('accAddBtn').textContent=tx('add');el('accIncludedTitle').textContent=tx('included');el('accBuilderNote').innerHTML=`<strong>${esc(tx('note'))}</strong>`;const cat=el('accCategory').value,brand=el('accBrand').value;populateCategories();if(cat){el('accCategory').value=cat;populateBrands();if(brand){el('accBrand').value=Array.from(el('accBrand').options).some(o=>o.value===brand)?brand:'ANY';populateTypes()}}renderTags()}
function enrichResult(p){const details=Array.isArray(p?.accessoire_details)?p.accessoire_details:[];const shown=details.filter(d=>d?.id&&d?.brand);if(!shown.length)return;const first=document.querySelector('#cards .card');if(!first)return;first.querySelector('.accessory-brand-summary')?.remove();const box=document.createElement('div');box.className='accessory-brand-summary';box.innerHTML=`<b>${esc(tx('details'))}:</b><br>${shown.map(d=>`${esc(baseLabel(d.id))} — ${esc(brandLabel(d.brand))}`).join('<br>')}`;first.appendChild(box)}
try{const baseFormState=formState;formState=function(){const p=baseFormState();p.accessoire_details=selectedDetailArray();return p};const baseApiPayload=apiPayload;apiPayload=function(){const p=baseApiPayload();p.accessoire_details=selectedDetailArray();return p};const baseFillForm=fillForm;fillForm=function(p){loadMeta(p?.accessoire_details||[]);baseFillForm(p);setTimeout(renderTags,0)};const baseSelectedLabels=selectedLabels;selectedLabels=function(){return Array.from(hidden.selectedOptions).map(o=>{const b=meta[o.value]?.brand;return b?`${o.textContent} (${brandLabel(b)})`:o.textContent})};const baseRender=render;render=function(data,p,save){baseRender(data,p,save);setTimeout(()=>enrichResult(p),0)}}catch(e){console.warn('Magic Book accessory bridge',e)}
restoreMetaFromDraft();populateCategories();refreshText();renderTags();el('accCategory').addEventListener('change',populateBrands);el('accBrand').addEventListener('change',populateTypes);el('accType').addEventListener('change',()=>{el('accAddBtn').disabled=!el('accType').value});el('accAddBtn').addEventListener('click',addAccessory);el('language').addEventListener('change',()=>setTimeout(refreshText,0));el('reset').addEventListener('click',()=>setTimeout(()=>{meta={};renderTags();try{saveDraft()}catch{}},0));
})();
