let lang=localStorage.getItem('magicbook-language')||'fr';if(!['fr','en'].includes(lang))lang='fr';let lastData=null,lastPayload=null;
function t(k){return I18N[lang][k]||I18N.fr[k]||k}function money(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat(lang==='fr'?'fr-CA':'en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(n):'N/D'}function vehicleName(p){return `${p.annee||''} ${p.marque||''} ${p.modele||''}`.trim()}
function buildBrands(){const current=$('marque').value;$('marque').innerHTML=BRANDS.map(b=>`<option>${esc(b)}</option>`).join('');$('marque').value=current&&BRANDS.includes(current)?current:'Yamaha'}
function buildAccessories(){const selected=new Set(Array.from($('accessoires').selectedOptions||[]).map(o=>o.value));$('accessoires').innerHTML=GROUPS.map(g=>`<optgroup label="${esc(lang==='fr'?g.fr:g.en)}">${g.items.map(i=>`<option value="${i[0]}" data-ref="${i[3]}">${esc(lang==='fr'?i[1]:i[2])}</option>`).join('')}</optgroup>`).join('');Array.from($('accessoires').options).forEach(o=>o.selected=selected.has(o.value))}
function conditionValue(){return document.querySelector('input[name=condition]:checked')?.value||'moyen'}function retention(age){if(age<=1)return .55;if(age===2)return .50;if(age<=4)return .42;if(age<=6)return .32;if(age<=9)return .22;return .15}function conditionMult(){const c=conditionValue();return c==='excellent'?1:c==='passable'?.65:.85}
function selectedIds(){return Array.from($('accessoires').selectedOptions).map(o=>o.value)}function selectedLabels(){return Array.from($('accessoires').selectedOptions).map(o=>o.textContent)}function accessoryReference(){return Array.from($('accessoires').selectedOptions).reduce((s,o)=>s+Number(o.dataset.ref||0),0)}
function updateAccessoryPreview(){const year=Number($('annee').value)||new Date().getFullYear(),age=Math.max(0,new Date().getFullYear()-year),rate=retention(age),ref=accessoryReference(),before=Math.round((ref*rate*conditionMult())/50)*50;$('accessoryImpact').innerHTML=`<b>${esc(t('referenceEquipment'))}: ${money(ref)}</b><br>${esc(t('retention'))}: <strong>${Math.round(rate*100)}%</strong> · ${esc(t('beforeCap'))}: <strong>${money(before)}</strong><br><span class="fine">${lang==='fr'?"Le plafond final est calculé après l'estimation de la machine et limite les accessoires à 35 % de la valeur de base.":'The final cap is calculated after the base vehicle estimate and limits accessories to 35% of the base value.'}</span>`}
function setCondition(value){document.querySelectorAll('.cond').forEach(card=>{const active=card.querySelector('input').value===value;card.classList.toggle('active',active);card.querySelector('input').checked=active})}
function formState(){return{marque:$('marque').value,modele:$('modele').value.trim(),annee:$('annee').value.trim(),millage_valeur:$('millage').value.trim(),millage_unite:$('usageUnit').value,accessoires:selectedIds(),autres_accessoires:$('autres').value.trim(),condition:conditionValue(),langue:lang}}
function apiPayload(){const p=formState(),unit=p.millage_unite==='h'?(lang==='fr'?'heures':'hours'):'km';return{...p,millage:p.millage_valeur?`${p.millage_valeur} ${unit}`:'0',usage_unit:p.millage_unite}}
function fillForm(p){if(!p)return;$('marque').value=BRANDS.includes(p.marque)?p.marque:'Yamaha';$('modele').value=p.modele||'';$('annee').value=p.annee||'';$('millage').value=p.millage_valeur||String(p.millage||'').match(/[\d.]+/)?.[0]||'';$('usageUnit').value=p.millage_unite||p.usage_unit||(/hour|heure|\bh\b/i.test(String(p.millage||''))?'h':'km');$('autres').value=p.autres_accessoires||'';buildAccessories();const ids=new Set(p.accessoires||[]);Array.from($('accessoires').options).forEach(o=>o.selected=ids.has(o.value));setCondition(p.condition||'excellent');updateAccessoryPreview();saveDraft()}
function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(formState()))}catch{}}
function restoreDraft(){try{const p=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(p)fillForm(p)}catch{}}
function getHistory(){try{const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(h)?h:[]}catch{return[]}}
function setHistory(h){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(h.slice(0,8)))}catch{}renderHistory()}
function saveHistory(data,p){const h=getHistory();const key=`${p.annee}|${p.marque}|${p.modele}|${p.millage_valeur}|${p.millage_unite}`.toLowerCase();const filtered=h.filter(x=>x.key!==key);filtered.unshift({id:Date.now(),key,at:new Date().toISOString(),payload:p,data});setHistory(filtered)}
function renderHistory(){const h=getHistory();$('historyPanel').style.display=h.length?'block':'none';$('historyList').innerHTML=h.map((x,i)=>`<div class="history-item"><b>${esc(vehicleName(x.payload))}</b><small>${esc(x.payload.millage_valeur||'0')} ${esc(x.payload.millage_unite||'km')} · ${new Date(x.at).toLocaleDateString(lang==='fr'?'fr-CA':'en-CA')}</small><div class="history-actions"><button class="mini" data-history-view="${i}" type="button">${esc(t('view'))}</button><button class="mini secondary" data-history-edit="${i}" type="button">${esc(t('modify'))}</button></div></div>`).join('');document.querySelectorAll('[data-history-view]').forEach(btn=>btn.onclick=()=>{const x=getHistory()[Number(btn.dataset.historyView)];if(x){lastData=x.data;lastPayload=x.payload;render(x.data,x.payload,false)}});document.querySelectorAll('[data-history-edit]').forEach(btn=>btn.onclick=()=>{const x=getHistory()[Number(btn.dataset.historyEdit)];if(x){fillForm(x.payload);$('results').style.display='none';$('form').style.display='block';window.scrollTo({top:0,behavior:'smooth'})}})}
function applyLanguage(){document.documentElement.lang=lang==='fr'?'fr-CA':'en-CA';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('language').value=lang;localStorage.setItem('magicbook-language',lang);buildAccessories();updateAccessoryPreview();renderHistory();refreshInstall();if(lastData&&lastPayload)render(lastData,lastPayload,false)}
function fail(m){$('loader').style.display='none';$('err').textContent=m;$('err').style.display='block';$('form').style.display='block';$('go').disabled=false}
async function evaluateNow(){const p=formState(),payload=apiPayload();if(!p.modele||!p.annee)return fail(t('required'));$('err').style.display='none';$('form').style.display='none';$('loader').style.display='block';$('go').disabled=true;try{const r=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify(payload)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Invalid server response.')}if(!r.ok)throw new Error(data.error||('HTTP '+r.status));lastData=data;lastPayload=p;saveHistory(data,p);render(data,p,false)}catch(e){fail(t('communication')+e.message)}}
function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}function marketUrl(platform,q){if(platform==='Kijiji')return`https://www.kijiji.ca/b-canada/${slug(q)}/k0l0`;if(platform==='Facebook Marketplace')return`https://www.facebook.com/marketplace/search/?query=${encodeURIComponent(q)}`;return`https://www.google.com/search?q=${encodeURIComponent('site:lespac.com '+q)}`}
function adText(data,p){const e=data.evaluation_ia,s=data.meta.sale_strategy,forts=(e.points_forts||[]).slice(0,3);return lang==='fr'?`🔥 À VENDRE — ${vehicleName(p)}\n\nPrix affiché suggéré : ${money(s.maximum_ask)}\nValeur de marché moyenne : ${money(s.average_sale)}\n\n✅ Points forts :\n${forts.map(x=>'• '+x).join('\n')}\n\n${p.millage_valeur?'Utilisation : '+p.millage_valeur+' '+p.millage_unite+'\n':''}${selectedLabels().length?'Équipements : '+selectedLabels().join(', ')+'\n':''}\nÉvaluation assistée par Magic Book.`:`🔥 FOR SALE — ${vehicleName(p)}\n\nSuggested asking price: ${money(s.maximum_ask)}\nAverage market value: ${money(s.average_sale)}\n\n✅ Strengths:\n${forts.map(x=>'• '+x).join('\n')}\n\n${p.millage_valeur?'Usage: '+p.millage_valeur+' '+p.millage_unite+'\n':''}${selectedLabels().length?'Equipment: '+selectedLabels().join(', ')+'\n':''}\nAI-assisted valuation by Magic Book.`}
function render(data,p,save=false){const e=data?.evaluation_ia;if(!e)return fail('Incomplete response.');if(save)saveHistory(data,p);const a=data.meta?.accessory_adjustment||{},s=data.meta?.sale_strategy||{},q=data.meta?.market_search_query||vehicleName(p),comps=Array.isArray(e.comparables_quebec)?e.comparables_quebec:[],forts=e.points_forts||[],faibles=e.points_faibles||[],v=vehicleName(p),contactTitle=t('contactTitle').replace('{vehicle}',v);const accessoryNames=(p.accessoires||[]).map(id=>GROUPS.flatMap(g=>g.items).find(i=>i[0]===id)).filter(Boolean).map(i=>lang==='fr'?i[1]:i[2]);
 $('cards').innerHTML=`
 <div class="card"><h2>${esc(t('vehicle'))}</h2><p><b>${esc(v)}</b><br>${esc(t('usage'))}: ${esc(p.millage_valeur||'0')} ${esc(p.millage_unite||'km')}<br>${esc(t('selectedAccessories'))}: ${accessoryNames.length?accessoryNames.map(esc).join(', '):esc(t('none'))}${p.autres_accessoires?'<br>'+esc(p.autres_accessoires):''}</p><p><b>${esc(t('referenceEquipment'))}:</b> ${money(a.reference_total||0)} · <b>${esc(t('retention'))}:</b> ${Math.round((a.retention_rate||0)*100)}%<br><b>${esc(t('finalContribution'))}:</b> +${money(a.retail||0)} · <b>${esc(t('tradeContribution'))}:</b> +${money(a.trade||0)}${a.cap_applied?`<br><span class="fine">⚠️ ${esc(t('capApplied'))}: ${money(a.cap_by_vehicle||0)}</span>`:''}</p></div>
 <div class="card"><h2>${esc(t('analysis'))}</h2><p>${esc(e.verdict_interne)}</p><p><em>${esc(t('reference'))}: ${money(e.blue_book?.valeur_officielle)} — ${esc(e.blue_book?.commentaire_ia)}</em></p><div class="proscons"><div class="listbox good"><h3>✅ ${esc(t('strengths'))}</h3><ul>${forts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="listbox weak"><h3>⚠️ ${esc(t('weaknesses'))}</h3><ul>${faibles.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></div>
 <div class="card sale"><h2>${esc(t('saleStrategy'))}</h2><div class="strategy-grid"><div class="strategy max"><b>${esc(t('maxAsk'))}</b><strong>${money(s.maximum_ask)}</strong></div><div class="strategy avg"><b>${esc(t('averageSale'))}</b><strong>${money(s.average_sale)}</strong></div><div class="strategy quick"><b>${esc(t('quickSale'))}</b><strong>${money(s.quick_sale)}</strong></div></div><p class="fine">${esc(t('strategyNote'))}</p></div>
 <div class="card"><h2>${esc(t('retail'))}</h2><div class="price">${money(e.prix_marche_particulier?.montant)}</div><p>${esc(e.prix_marche_particulier?.realite_du_marche)}</p><h3>${esc(t('comparables'))}</h3>${comps.map(c=>`<div class="comp"><div class="comp-head"><div><b>${esc(c.plateforme)}</b><br>${esc(c.titre_annonce)}</div><div class="comp-price">${money(c.prix_affiche)}</div></div><a href="${marketUrl(c.plateforme,q)}" target="_blank" rel="noopener">🔗 ${esc(t('viewReal'))}</a></div>`).join('')}<p class="fine">${esc(t('marketNote'))}</p><h3>${esc(t('marketLinks'))}</h3><div class="market-grid"><a class="market-link kijiji" target="_blank" rel="noopener" href="${marketUrl('Kijiji',q)}">Kijiji</a><a class="market-link lespac" target="_blank" rel="noopener" href="${marketUrl('LesPAC',q)}">LesPAC</a><a class="market-link fb" target="_blank" rel="noopener" href="${marketUrl('Facebook Marketplace',q)}">Facebook Marketplace</a></div><p class="fine">${esc(t('engine'))}: ${esc(data.meta?.model||'Gemini')}</p></div>
 <div class="card social"><h2>${esc(t('sellFacebook'))}</h2><p>${esc(t('sellNote'))}</p><div class="result-actions social-actions"><button id="copyAd" class="action copy" type="button">${esc(t('copyAd'))}</button><a class="action facebook" target="_blank" rel="noopener" href="https://www.facebook.com/share/g/1K1cSWzdhK/">${esc(t('openFacebook'))}</a></div></div>
 <div class="card contact"><div class="contact-kicker">${esc(t('contactKicker'))}</div><div class="contact-title">${esc(contactTitle)}</div><p>${esc(t('contactText'))}</p><div class="contact-grid"><a class="contact-link call" href="tel:+18196239445">${esc(t('call'))}<br><small>819-623-9445 poste 223</small></a><a class="contact-link sms" href="sms:+18196162202">${esc(t('sms'))}<br><small>819-616-2202</small></a><a class="contact-link email" href="mailto:Jonathan@theorecreo.com?subject=${encodeURIComponent((lang==='fr'?'Remplacer mon ':'Replace my ')+v)}">${esc(t('email'))}<br><small>Jonathan@theorecreo.com</small></a><a class="contact-link web" href="https://theorecreo.com" target="_blank" rel="noopener">${esc(t('website'))}<br><small>theorecreo.com</small></a></div></div>
 <div class="card exchange"><h2>${esc(t('tradeTitle'))}</h2><p class="dealer-note">${esc(t('tradeText'))}</p><div class="fine">${esc(t('tradeLabel'))}</div><div class="price">${money(e.prix_echange_concessionnaire?.montant)}</div><p><b>${esc(t('argument'))}:</b> ${esc(e.prix_echange_concessionnaire?.argument_de_negociation)}</p><div class="tax-note">💡 ${esc(t('taxNote'))}</div></div>`;
 const copy=$('copyAd');if(copy)copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(adText(data,p));copy.textContent='✅ '+t('copied')}catch{alert(adText(data,p))}});$('loader').style.display='none';$('form').style.display='none';$('results').style.display='block';$('go').disabled=false;window.scrollTo({top:0,behavior:'smooth'})}
function editCurrent(){if(lastPayload)fillForm(lastPayload);$('results').style.display='none';$('form').style.display='block';window.scrollTo({top:0,behavior:'smooth'})}function resetApp(){$('results').style.display='none';$('err').style.display='none';$('form').style.display='block';lastData=null;lastPayload=null;$('modele').value='';$('annee').value='';$('millage').value='';$('autres').value='';Array.from($('accessoires').options).forEach(o=>o.selected=false);setCondition('excellent');updateAccessoryPreview();saveDraft();window.scrollTo({top:0,behavior:'smooth'})}
$('language').addEventListener('change',()=>{lang=$('language').value;applyLanguage()});['marque','modele','annee','millage','usageUnit','accessoires','autres'].forEach(id=>$(id).addEventListener(id==='modele'||id==='annee'||id==='millage'||id==='autres'?'input':'change',()=>{saveDraft();updateAccessoryPreview()}));document.querySelectorAll('.cond').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.cond').forEach(c=>c.classList.remove('active'));card.classList.add('active');card.querySelector('input').checked=true;saveDraft();updateAccessoryPreview()}));$('go').addEventListener('click',evaluateNow);$('reset').addEventListener('click',resetApp);$('editBtn').addEventListener('click',editCurrent);$('printBtn').addEventListener('click',()=>window.print());$('clearHistory').addEventListener('click',()=>{if(confirm(lang==='fr'?'Effacer les évaluations sauvegardées sur cet appareil?':'Clear saved evaluations on this device?'))setHistory([])});
let deferredInstall=null;const installBtn=$('install'),installHelp=$('installHelp'),installStatus=$('installStatus'),steps=$('steps');const isStandalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;function refreshInstall(){if(isStandalone()){installBtn.textContent=lang==='fr'?'✅ Application installée sur cet appareil':'✅ App installed on this device';installBtn.disabled=true;installStatus.textContent=lang==='fr'?'Magic Book fonctionne déjà en mode application.':'Magic Book is already running as an installed app.';installHelp.style.display='none'}else{installBtn.disabled=false;installBtn.textContent=deferredInstall?(lang==='fr'?"📲 Installer l'application maintenant":'📲 Install the app now'):t('install');installStatus.textContent=deferredInstall?(lang==='fr'?'Installation automatique disponible.':'Automatic installation is available.'):t('installStatus')}}function manualInstall(){const ua=navigator.userAgent;steps.innerHTML=/iphone|ipad|ipod/i.test(ua)?(lang==='fr'?'<ol><li>Ouvre le bouton Partager.</li><li>Choisis « Sur l’écran d’accueil ».</li><li>Appuie sur Ajouter.</li></ol>':'<ol><li>Open Share.</li><li>Choose “Add to Home Screen”.</li><li>Tap Add.</li></ol>'):(/android/i.test(ua)?(lang==='fr'?'<ol><li>Ouvre le menu ⋮ de Chrome.</li><li>Choisis « Installer l’application » ou « Ajouter à l’écran d’accueil ».</li><li>Confirme.</li></ol>':'<ol><li>Open Chrome’s ⋮ menu.</li><li>Choose “Install app” or “Add to Home screen”.</li><li>Confirm.</li></ol>'):'<ol><li>Open the browser menu.</li><li>Choose Install / Add to Home screen.</li></ol>');installHelp.style.display='block'}window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;refreshInstall()});installBtn.addEventListener('click',async()=>{if(isStandalone())return;if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;refreshInstall()}else manualInstall()});window.addEventListener('appinstalled',()=>{deferredInstall=null;refreshInstall()});
buildBrands();buildAccessories();$('language').value=lang;restoreDraft();applyLanguage();window.addEventListener('load',async()=>{if('serviceWorker'in navigator){try{const r=await navigator.serviceWorker.register('/sw.js?v=330',{scope:'/'});r.update()}catch(e){console.warn(e)}}});