(()=>{
const SESSION_KEY='magicbook-auth-session-v1';
const PENDING_KEY='magicbook-auth-pending-v1';
const $=id=>document.getElementById(id);
const getLang=()=>($('language')?.value==='en'?'en':'fr');
const copy={
 fr:{signedOut:'Connecte-toi par courriel pour retrouver tes évaluations sur tous tes appareils.',ready:'Connexion cloud active',wait:'Connexion cloud à activer',email:'Adresse courriel',type:'Type de compte',private:'Particulier',pro:'Professionnel',send:'Recevoir mon code',resend:'Renvoyer le code',sending:'Envoi en cours…',sent:'Code envoyé par courriel. Entre les 6 chiffres ci-dessous pour te connecter.',notReady:'La connexion cloud n’est pas disponible pour le moment.',invalid:'Entre une adresse courriel valide.',code:'Code de connexion',codeHint:'Entre le code à 6 chiffres reçu par courriel.',verify:'Me connecter',verifying:'Vérification…',invalidCode:'Entre le code à 6 chiffres reçu par courriel.',verified:'Connexion réussie. Synchronisation de ton Magic Book…',back:'Changer de courriel',connected:'Connecté',logout:'Déconnexion',marketing:'Oui, je souhaite recevoir les promotions, nouveautés et offres de Théo Récréo par courriel. Je pourrai me désabonner en tout temps.',marketingShort:'Promotions Théo Récréo autorisées',noMarketing:'Aucun consentement marketing',privacy:'Le compte fonctionne même sans accepter les communications promotionnelles.',error:'Impossible de compléter la connexion pour le moment.',synced:'Historique cloud synchronisé',syncing:'Synchronisation…'},
 en:{signedOut:'Sign in by email to access your evaluations on all your devices.',ready:'Cloud sign-in active',wait:'Cloud sign-in to activate',email:'Email address',type:'Account type',private:'Individual',pro:'Professional',send:'Send my code',resend:'Resend code',sending:'Sending…',sent:'Code sent by email. Enter the 6 digits below to sign in.',notReady:'Cloud sign-in is not available right now.',invalid:'Enter a valid email address.',code:'Sign-in code',codeHint:'Enter the 6-digit code you received by email.',verify:'Sign in',verifying:'Verifying…',invalidCode:'Enter the 6-digit code you received by email.',verified:'Sign-in successful. Syncing your Magic Book…',back:'Change email',connected:'Signed in',logout:'Sign out',marketing:'Yes, I want to receive promotions, news and offers from Théo Récréo by email. I can unsubscribe at any time.',marketingShort:'Théo Récréo promotions allowed',noMarketing:'No marketing consent',privacy:'Your account works even if you do not agree to promotional emails.',error:'Unable to complete sign-in right now.',synced:'Cloud history synced',syncing:'Syncing…'}
};
const tx=k=>copy[getLang()][k]||k;
let authEnabled=false,currentUser=null,currentProfile=null,bridgeInstalled=false,codeStep=false,pendingAuth=null;
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
function cleanCode(v){return String(v||'').replace(/\D/g,'').slice(0,6)}
function setMsg(text,type=''){const el=$('accountMessage');if(!el)return;el.textContent=text||'';el.className='account-message'+(text?' show':'')+(type?' '+type:'')}
function saveSession(s){try{localStorage.setItem(SESSION_KEY,JSON.stringify(s))}catch{}}
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function clearSession(){try{localStorage.removeItem(SESSION_KEY)}catch{}currentUser=null;currentProfile=null}
function savePending(p){pendingAuth=p;try{sessionStorage.setItem(PENDING_KEY,JSON.stringify(p))}catch{}}
function getPending(){if(pendingAuth)return pendingAuth;try{pendingAuth=JSON.parse(sessionStorage.getItem(PENDING_KEY)||'null')}catch{pendingAuth=null}return pendingAuth}
function clearPending(){pendingAuth=null;try{sessionStorage.removeItem(PENDING_KEY)}catch{}}
function accountKind(){return currentProfile?.account_type==='professionnel'||currentUser?.user_metadata?.user_type==='professionnel'?'professionnel':'particulier'}
function marketingAllowed(){return accountKind()==='particulier'&&(currentProfile?.marketing_consent===true||currentUser?.user_metadata?.marketing_consent===true)}
function setTexts(){if(!$('accountPanel'))return;$('accountSub').textContent=tx('signedOut');$('accountEmailLabel').textContent=tx('email');$('accountTypeLabel').textContent=tx('type');$('accountType').options[0].textContent=tx('private');$('accountType').options[1].textContent=tx('pro');$('accountSubmit').textContent=codeStep?tx('resend'):tx('send');$('accountConsentText').textContent=tx('marketing');$('accountPrivacyText').firstChild.textContent=tx('privacy')+' ';$('accountLogout').textContent=tx('logout');if($('accountCodeLabel'))$('accountCodeLabel').textContent=tx('code');if($('accountCodeHint'))$('accountCodeHint').textContent=tx('codeHint');if($('accountVerify'))$('accountVerify').textContent=tx('verify');if($('accountBack'))$('accountBack').textContent=tx('back');updateBadge();renderUser()}
function updateBadge(){const b=$('accountBadge');if(!b)return;b.textContent=authEnabled?'● '+tx('ready'):'● '+tx('wait');b.className='account-badge '+(authEnabled?'ready':'wait')}
function updateConsentVisibility(){const box=$('accountConsent');if(!box)return;box.style.display=$('accountType').value==='particulier'?'flex':'none';if($('accountType').value!=='particulier')$('marketingConsent').checked=false}
function setCodeStep(active){codeStep=!!active;const wrap=$('accountCodeWrap');if(wrap)wrap.classList.toggle('show',codeStep);const email=$('accountEmail'),type=$('accountType'),consent=$('marketingConsent');if(email)email.disabled=codeStep;if(type)type.disabled=codeStep;if(consent)consent.disabled=codeStep;if($('accountSubmit'))$('accountSubmit').textContent=codeStep?tx('resend'):tx('send');if(codeStep&&$('accountCode'))setTimeout(()=>$('accountCode').focus(),50)}
function resetCodeStep(){setCodeStep(false);clearPending();if($('accountCode'))$('accountCode').value='';setMsg('', '')}
function renderUser(){const form=$('accountForm'),profile=$('accountProfile');if(!form||!profile)return;if(!currentUser){form.style.display='grid';profile.classList.remove('show');return}form.style.display='none';profile.classList.add('show');$('accountAvatar').textContent=(currentUser.email||'?').slice(0,1).toUpperCase();$('accountEmailText').textContent=currentUser.email||'';const kind=accountKind()==='professionnel'?tx('pro'):tx('private'),m=marketingAllowed()?tx('marketingShort'):tx('noMarketing');$('accountMeta').textContent=`${kind} · ${m}`}
async function api(action,body,method='POST'){const r=await fetch(`/api/auth?action=${encodeURIComponent(action)}`,{method,headers:{'Content-Type':'application/json'},cache:'no-store',body:method==='GET'?undefined:JSON.stringify(body||{})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function clientKey(p){return `${p?.annee||''}|${p?.marque||''}|${p?.modele||''}|${p?.millage_valeur||''}|${p?.millage_unite||''}`.toLowerCase()}
async function cloudSave(data,p){const s=getSession();if(!currentUser||!s?.access_token||!data||!p)return;try{await api('save-evaluation',{access_token:s.access_token,client_key:clientKey(p),vehicle_name:typeof vehicleName==='function'?vehicleName(p):`${p.annee||''} ${p.marque||''} ${p.modele||''}`.trim(),payload:p,result:data})}catch(e){console.warn('Magic Book cloud save:',e.message||e)}}
async function syncCloudHistory(){const s=getSession();if(!currentUser||!s?.access_token||typeof getHistory!=='function'||typeof setHistory!=='function')return;try{setMsg(tx('syncing'),'');const data=await api('history',{access_token:s.access_token});const cloud=(data.evaluations||[]).map(row=>({id:row.id,key:row.client_key,at:row.updated_at||row.created_at,payload:row.payload,data:row.result}));const local=getHistory();const merged=[...cloud,...local].sort((a,b)=>new Date(b.at||0)-new Date(a.at||0));const seen=new Set(),unique=[];for(const item of merged){const key=item.key||clientKey(item.payload);if(!key||seen.has(key))continue;seen.add(key);unique.push({...item,key});if(unique.length>=20)break}setHistory(unique);for(const item of local.slice(0,8))cloudSave(item.data,item.payload);setMsg(tx('synced'),'success')}catch(e){console.warn('Magic Book cloud sync:',e.message||e);setMsg('', '')}}
function installHistoryBridge(){if(bridgeInstalled||typeof saveHistory!=='function')return;bridgeInstalled=true;const originalSaveHistory=saveHistory;saveHistory=function(data,p){const out=originalSaveHistory(data,p);cloudSave(data,p);return out}}
async function status(){try{const data=await api('status',null,'GET');authEnabled=!!data.enabled}catch{authEnabled=false}updateBadge();if(!authEnabled)setMsg(tx('notReady'),'')}
async function loadUser(){const s=getSession();if(!s?.access_token)return;try{const data=await api('me',{access_token:s.access_token});currentUser=data.user;currentProfile=data.profile||null;renderUser();installHistoryBridge();await syncCloudHistory()}catch{if(s.refresh_token){try{const r=await api('refresh',{refresh_token:s.refresh_token});const next=r.session||r;saveSession(next);const data=await api('me',{access_token:next.access_token});currentUser=data.user;currentProfile=data.profile||null;renderUser();installHistoryBridge();await syncCloudHistory();return}catch{}}clearSession();renderUser()}}
function captureCallback(){const raw=location.hash.startsWith('#')?location.hash.slice(1):'';if(!raw)return false;const p=new URLSearchParams(raw);const access=p.get('access_token'),refresh=p.get('refresh_token');if(!access)return false;const session={access_token:access,refresh_token:refresh||'',expires_in:Number(p.get('expires_in')||0),expires_at:Number(p.get('expires_at')||0),token_type:p.get('token_type')||'bearer'};saveSession(session);history.replaceState({},document.title,location.pathname+location.search.replace(/([?&])auth=callback(&|$)/,'$1').replace(/[?&]$/,''));setMsg(tx('verified'),'success');return true}
async function sendCode(){const email=$('accountEmail').value.trim(),type=$('accountType').value;if(!validEmail(email))return setMsg(tx('invalid'),'error');if(!authEnabled)return setMsg(tx('notReady'),'error');const pending={email,user_type:type,marketing_consent:type==='particulier'&&$('marketingConsent').checked,locale:getLang()};savePending(pending);$('accountSubmit').disabled=true;$('accountSubmit').textContent=tx('sending');setMsg('', '');try{await api('send-code',pending);setCodeStep(true);setMsg(tx('sent'),'success')}catch(e){setMsg(`${tx('error')} ${e.message||''}`.trim(),'error')}finally{$('accountSubmit').disabled=false;$('accountSubmit').textContent=codeStep?tx('resend'):tx('send')}}
async function verifyCode(){const pending=getPending(),email=pending?.email||$('accountEmail').value.trim(),token=cleanCode($('accountCode')?.value);if(!validEmail(email))return setMsg(tx('invalid'),'error');if(token.length!==6)return setMsg(tx('invalidCode'),'error');$('accountVerify').disabled=true;$('accountVerify').textContent=tx('verifying');setMsg('', '');try{const data=await api('verify-code',{email,token,account_type:pending?.user_type||$('accountType').value,marketing_consent:pending?.marketing_consent===true});saveSession(data.session);currentUser=data.user;currentProfile=data.profile||null;clearPending();setCodeStep(false);renderUser();installHistoryBridge();setMsg(tx('verified'),'success');await syncCloudHistory()}catch(e){setMsg(`${tx('error')} ${e.message||''}`.trim(),'error')}finally{$('accountVerify').disabled=false;$('accountVerify').textContent=tx('verify')}}
async function logout(){const s=getSession();try{if(s?.access_token)await api('logout',{access_token:s.access_token})}catch{}clearSession();resetCodeStep();renderUser();setMsg('', '')}
async function init(){if(!$('accountPanel'))return;captureCallback();setTexts();updateConsentVisibility();const pending=getPending();if(pending?.email){$('accountEmail').value=pending.email;$('accountType').value=pending.user_type==='professionnel'?'professionnel':'particulier';$('marketingConsent').checked=pending.marketing_consent===true;updateConsentVisibility();setCodeStep(true)}$('accountType').addEventListener('change',updateConsentVisibility);$('accountSubmit').addEventListener('click',sendCode);$('accountEmail').addEventListener('keydown',e=>{if(e.key==='Enter'&&!codeStep){e.preventDefault();sendCode()}});$('accountCode')?.addEventListener('input',e=>{e.target.value=cleanCode(e.target.value)});$('accountCode')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();verifyCode()}});$('accountVerify')?.addEventListener('click',verifyCode);$('accountBack')?.addEventListener('click',resetCodeStep);$('accountLogout').addEventListener('click',logout);$('language')?.addEventListener('change',()=>setTimeout(setTexts,0));installHistoryBridge();await status();await loadUser()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
