(()=>{
const SESSION_KEY='magicbook-auth-session-v1';
const $=id=>document.getElementById(id);
const getLang=()=>($('language')?.value==='en'?'en':'fr');
const copy={
 fr:{signedOut:'Connecte-toi par courriel pour retrouver ton compte sur plusieurs appareils.',ready:'Connexion sécurisée',wait:'Connexion cloud à activer',email:'Adresse courriel',type:'Type de compte',private:'Particulier',pro:'Professionnel',send:'M’envoyer mon lien de connexion',sending:'Envoi en cours…',sent:'Lien envoyé. Ouvre ton courriel et touche le lien pour revenir dans Magic Book.',notReady:'Le module de connexion est prêt dans l’application, mais le service Supabase doit encore être connecté pour l’activer.',invalid:'Entre une adresse courriel valide.',connected:'Connecté',logout:'Déconnexion',marketing:'Oui, je souhaite recevoir les promotions, nouveautés et offres de Théo Récréo par courriel. Je pourrai me désabonner en tout temps.',marketingShort:'Promotions Théo Récréo autorisées',noMarketing:'Aucun consentement marketing',privacy:'En créant un compte, tu peux continuer à utiliser Magic Book sans accepter les communications promotionnelles.',error:'Impossible de compléter la connexion pour le moment.'},
 en:{signedOut:'Sign in by email to access your account across devices.',ready:'Secure sign-in',wait:'Cloud sign-in to activate',email:'Email address',type:'Account type',private:'Individual',pro:'Professional',send:'Email me a sign-in link',sending:'Sending…',sent:'Link sent. Open your email and tap the link to return to Magic Book.',notReady:'The sign-in module is ready in the app, but Supabase still needs to be connected before it can be activated.',invalid:'Enter a valid email address.',connected:'Signed in',logout:'Sign out',marketing:'Yes, I want to receive promotions, news and offers from Théo Récréo by email. I can unsubscribe at any time.',marketingShort:'Théo Récréo promotions allowed',noMarketing:'No marketing consent',privacy:'You can create an account and keep using Magic Book without agreeing to promotional emails.',error:'Unable to complete sign-in right now.'}
};
const tx=k=>copy[getLang()][k]||k;
let authEnabled=false,currentUser=null;
function validEmail(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||'').trim())}
function setMsg(text,type=''){const el=$('accountMessage');if(!el)return;el.textContent=text||'';el.className='account-message'+(text?' show':'')+(type?' '+type:'')}
function saveSession(s){try{localStorage.setItem(SESSION_KEY,JSON.stringify(s))}catch{}}
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function clearSession(){try{localStorage.removeItem(SESSION_KEY)}catch{}currentUser=null}
function setTexts(){if(!$('accountPanel'))return;$('accountSub').textContent=tx('signedOut');$('accountEmailLabel').textContent=tx('email');$('accountTypeLabel').textContent=tx('type');$('accountType').options[0].textContent=tx('private');$('accountType').options[1].textContent=tx('pro');$('accountSubmit').textContent=tx('send');$('accountConsentText').textContent=tx('marketing');$('accountPrivacyText').firstChild.textContent=tx('privacy')+' ';$('accountLogout').textContent=tx('logout');updateBadge();renderUser()}
function updateBadge(){const b=$('accountBadge');if(!b)return;b.textContent=authEnabled?'● '+tx('ready'):'● '+tx('wait');b.className='account-badge '+(authEnabled?'ready':'wait')}
function updateConsentVisibility(){const box=$('accountConsent');if(!box)return;box.style.display=$('accountType').value==='particulier'?'flex':'none';if($('accountType').value!=='particulier')$('marketingConsent').checked=false}
function renderUser(){const form=$('accountForm'),profile=$('accountProfile');if(!form||!profile)return;if(!currentUser){form.style.display='grid';profile.classList.remove('show');return}form.style.display='none';profile.classList.add('show');$('accountAvatar').textContent=(currentUser.email||'?').slice(0,1).toUpperCase();$('accountEmailText').textContent=currentUser.email||'';const md=currentUser.user_metadata||{},kind=md.user_type==='professionnel'?tx('pro'):tx('private'),m=md.marketing_consent===true?tx('marketingShort'):tx('noMarketing');$('accountMeta').textContent=`${kind} · ${m}`;setMsg('', '')}
async function api(action,body,method='POST'){const r=await fetch(`/api/auth?action=${encodeURIComponent(action)}`,{method,headers:{'Content-Type':'application/json'},cache:'no-store',body:method==='GET'?undefined:JSON.stringify(body||{})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function status(){try{const data=await api('status',null,'GET');authEnabled=!!data.enabled}catch{authEnabled=false}updateBadge();if(!authEnabled)setMsg(tx('notReady'),'')}
async function loadUser(){const s=getSession();if(!s?.access_token)return;try{const data=await api('me',{access_token:s.access_token});currentUser=data.user;renderUser()}catch{if(s.refresh_token){try{const r=await api('refresh',{refresh_token:s.refresh_token});const next=r.session||r;saveSession(next);const data=await api('me',{access_token:next.access_token});currentUser=data.user;renderUser();return}catch{}}clearSession();renderUser()}}
function captureCallback(){const raw=location.hash.startsWith('#')?location.hash.slice(1):'';if(!raw)return false;const p=new URLSearchParams(raw);const access=p.get('access_token'),refresh=p.get('refresh_token');if(!access)return false;const session={access_token:access,refresh_token:refresh||'',expires_in:Number(p.get('expires_in')||0),expires_at:Number(p.get('expires_at')||0),token_type:p.get('token_type')||'bearer'};saveSession(session);history.replaceState({},document.title,location.pathname+location.search.replace(/([?&])auth=callback(&|$)/,'$1').replace(/[?&]$/,''));setMsg(getLang()==='fr'?'Connexion réussie. Bienvenue dans Magic Book.':'Sign-in successful. Welcome to Magic Book.','success');return true}
async function sendLink(){const email=$('accountEmail').value.trim(),type=$('accountType').value;if(!validEmail(email))return setMsg(tx('invalid'),'error');if(!authEnabled)return setMsg(tx('notReady'),'error');$('accountSubmit').disabled=true;$('accountSubmit').textContent=tx('sending');setMsg('', '');try{await api('send-link',{email,user_type:type,marketing_consent:type==='particulier'&&$('marketingConsent').checked,locale:getLang()});setMsg(tx('sent'),'success')}catch(e){setMsg(`${tx('error')} ${e.message||''}`.trim(),'error')}finally{$('accountSubmit').disabled=false;$('accountSubmit').textContent=tx('send')}}
async function logout(){const s=getSession();try{if(s?.access_token)await api('logout',{access_token:s.access_token})}catch{}clearSession();renderUser();setMsg('', '')}
async function init(){if(!$('accountPanel'))return;captureCallback();setTexts();updateConsentVisibility();$('accountType').addEventListener('change',updateConsentVisibility);$('accountSubmit').addEventListener('click',sendLink);$('accountEmail').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendLink()}});$('accountLogout').addEventListener('click',logout);$('language')?.addEventListener('change',()=>setTimeout(setTexts,0));await status();await loadUser()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
